[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = true
ffi = false
fs_permissions = [{ access = "read", path = "./config" }]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 32
fail_on_revert = true
